// <auto-generated />
using System;
using ExAVReservas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExAVReservas.Migrations
{
    [DbContext(typeof(ExAPVRContext))]
    [Migration("20210522033944_MyfirstMigration")]
    partial class MyfirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExAVReservas.Models.CategoryEventModel", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("IdEvent");

                    b.ToTable("eventModels");
                });

            modelBuilder.Entity("ExAVReservas.Models.ClientModel", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("clientModels");
                });

            modelBuilder.Entity("ExAVReservas.Models.FurnitureModel", b =>
                {
                    b.Property<int>("IdFurniture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("ReservationDetailIdDetail")
                        .HasColumnType("int");

                    b.HasKey("IdFurniture");

                    b.HasIndex("ReservationDetailIdDetail");

                    b.ToTable("furnitureModels");
                });

            modelBuilder.Entity("ExAVReservas.Models.ReservationDetail", b =>
                {
                    b.Property<int>("IdDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdFurniture")
                        .HasColumnType("int");

                    b.Property<int>("IdReseration")
                        .HasColumnType("int");

                    b.Property<int?>("IdReservation")
                        .HasColumnType("int");

                    b.HasKey("IdDetail");

                    b.HasIndex("IdFurniture");

                    b.HasIndex("IdReservation");

                    b.ToTable("reservationDetails");
                });

            modelBuilder.Entity("ExAVReservas.Models.ReservationModel", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateDue")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.HasKey("IdReservation");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEvent");

                    b.ToTable("reservationModels");
                });

            modelBuilder.Entity("ExAVReservas.Models.FurnitureModel", b =>
                {
                    b.HasOne("ExAVReservas.Models.ReservationDetail", null)
                        .WithMany("furnitureList")
                        .HasForeignKey("ReservationDetailIdDetail");
                });

            modelBuilder.Entity("ExAVReservas.Models.ReservationDetail", b =>
                {
                    b.HasOne("ExAVReservas.Models.FurnitureModel", "furniture")
                        .WithMany()
                        .HasForeignKey("IdFurniture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExAVReservas.Models.ReservationModel", "reservation")
                        .WithMany()
                        .HasForeignKey("IdReservation");

                    b.Navigation("furniture");

                    b.Navigation("reservation");
                });

            modelBuilder.Entity("ExAVReservas.Models.ReservationModel", b =>
                {
                    b.HasOne("ExAVReservas.Models.ClientModel", "client")
                        .WithMany()
                        .HasForeignKey("IdCliente");

                    b.HasOne("ExAVReservas.Models.CategoryEventModel", "categoryEvent")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoryEvent");

                    b.Navigation("client");
                });

            modelBuilder.Entity("ExAVReservas.Models.ReservationDetail", b =>
                {
                    b.Navigation("furnitureList");
                });
#pragma warning restore 612, 618
        }
    }
}
